#%RAML 1.0 DataType

properties:
  id:
    example: 1
    type: number
    format: int
  name:
    example: Esmeralda
    type: string
  bio:
    example: 20+ years of experience in IT and very smart.
    type: string